name: Flutter Web Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3' 

      - name: Install dependencies
        run: flutter pub get

      - name: Build for web
        run: flutter build web
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
            SOURCE: "build/web/"
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: ${{ secrets.REMOTE_TARGET }}
            REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
